Repository INSPJT/instagram_clone_backend, pull requests merged in 2021-02, with the labels that each got.

#4 docs: Update README
  README.md
Labels: documentation

#5 docs: Add github pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#8 feat : Add DB_CLOSE_DELAY
  src/main/resources/application.yml
Labels: build

#7 Create gradle.yml
  .github/workflows/gradle.yml
Labels: enhancement

#9 feat : edit datasource url for CI
  src/test/resources/application.yml
Labels: enhancement

#10 Add Config for Test Coverage
  .github/workflows/gradle.yml
  README.md
  build.gradle
Labels: enhancement

#13 feat : Add Coverage Rule in CI
  .github/workflows/gradle.yml
Labels: enhancement

#20 chore : Add Cascade Option
  src/main/java/our/yurivongella/instagramclone/domain/comment/Comment.java
  src/main/java/our/yurivongella/instagramclone/domain/comment/CommentLike.java
  src/main/java/our/yurivongella/instagramclone/domain/comment/CommentLikeRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/member/Member.java
  src/main/java/our/yurivongella/instagramclone/domain/post/Post.java
Labels: enhancement
