Repository INSPJT/instagram_clone_backend, pull requests merged in 2021-04, with the labels that each got.

#76 chore: 피드 조회할 때 lastPostId 파라미터 optional 로 변경
  src/main/java/our/yurivongella/instagramclone/controller/FeedController.java
  src/main/java/our/yurivongella/instagramclone/service/PostService.java
  src/test/java/our/yurivongella/instagramclone/service/PostServiceTest.java
Labels: fix

#77 2021. 04. 03. 배포
  src/main/java/our/yurivongella/instagramclone/controller/FeedController.java
  src/main/java/our/yurivongella/instagramclone/controller/MemberController.java
  src/main/java/our/yurivongella/instagramclone/controller/PostController.java
  src/main/java/our/yurivongella/instagramclone/controller/ProfileController.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/MediaUrlDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/PostReadResponseDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/profile/ProfileDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/profile/ProfileMemberDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/profile/ProfilePostDto.java
  src/main/java/our/yurivongella/instagramclone/domain/comment/Comment.java
  src/main/java/our/yurivongella/instagramclone/domain/follow/Follow.java
  src/main/java/our/yurivongella/instagramclone/domain/follow/FollowRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/member/Member.java
  src/main/java/our/yurivongella/instagramclone/domain/post/MediaUrl.java
  src/main/java/our/yurivongella/instagramclone/domain/post/Post.java
  src/main/java/our/yurivongella/instagramclone/domain/post/PostLikeRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/post/PostRepository.java
  src/main/java/our/yurivongella/instagramclone/service/CommentService.java
  src/main/java/our/yurivongella/instagramclone/service/MemberService.java
  src/main/java/our/yurivongella/instagramclone/service/PostService.java
  src/main/java/our/yurivongella/instagramclone/service/ProfileService.java
  src/main/java/our/yurivongella/instagramclone/util/DateTimeUtil.java
  src/main/resources/data.sql
  src/test/java/our/yurivongella/instagramclone/service/CommentServiceTest.java
  src/test/java/our/yurivongella/instagramclone/service/MemberServiceTest.java
  src/test/java/our/yurivongella/instagramclone/service/PostServiceTest.java
  src/test/java/our/yurivongella/instagramclone/service/ProfileServiceTest.java
Labels: release

#78 test
  Dockerfile
Labels: test

#79 ci/cd test (#78)
  Dockerfile
Labels: test

#80 Add logging as file
  .github/workflows/cicd.yml
  Dockerfile
  src/main/resources/application.yml
Labels: build

#82 Master conflict resolve
  .github/workflows/cicd.yml
  Dockerfile
  src/main/resources/application.yml
Labels: fix

#87 중복 check api 추가
  src/main/java/our/yurivongella/instagramclone/controller/AuthController.java
  src/main/java/our/yurivongella/instagramclone/exception/ErrorCode.java
  src/main/java/our/yurivongella/instagramclone/service/AuthService.java
  src/main/resources/aws.yml
  src/test/java/our/yurivongella/instagramclone/service/AuthServiceTest.java
Labels: enhancement

#88 feat: 내 정보 간단하게 조회하는 API 추가
  src/main/java/our/yurivongella/instagramclone/controller/ProfileController.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/profile/SimpleProfileDto.java
  src/main/java/our/yurivongella/instagramclone/service/ProfileService.java
  src/test/java/our/yurivongella/instagramclone/service/ProfileServiceTest.java
Labels: enhancement
