Repository INSPJT/instagram_clone_backend, pull requests merged in 2021-03, with the labels that each got.

#22 feat : Add configuration (profiles)
  build.gradle
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: enhancement

#23 Add Dockerfile and CORS
  Dockerfile
  build.gradle
  src/main/java/our/yurivongella/instagramclone/config/WebConfig.java
  src/main/resources/application.yml
Labels: enhancement

#24 feat: fix Default profile, allow all origin
  Docker-compose.yml
  Dockerfile
  build.gradle
  src/main/java/our/yurivongella/instagramclone/config/WebConfig.java
  src/main/resources/application.yml
Labels: fix

#25 feat : merge feat Post
  src/main/java/our/yurivongella/instagramclone/controller/AuthController.java
  src/main/java/our/yurivongella/instagramclone/controller/MemberController.java
  src/main/java/our/yurivongella/instagramclone/controller/PostController.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/CommentResponseDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/MemberDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/PostCreateRequestDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/PostReadResponseDto.java
  src/main/java/our/yurivongella/instagramclone/domain/post/PictureURL.java
  src/main/java/our/yurivongella/instagramclone/domain/post/Post.java
  src/main/java/our/yurivongella/instagramclone/service/PostService.java
  src/test/java/our/yurivongella/instagramclone/service/PostServiceTest.java
Labels: enhancement

#29 Member 도메인 리팩토링
  src/main/java/our/yurivongella/instagramclone/controller/dto/SigninRequestDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/SignupRequestDto.java
  src/main/java/our/yurivongella/instagramclone/domain/follow/Follow.java
  src/main/java/our/yurivongella/instagramclone/domain/follow/FollowRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/member/Member.java
  src/main/java/our/yurivongella/instagramclone/domain/member/MemberRepository.java
  src/main/java/our/yurivongella/instagramclone/service/AuthService.java
  src/main/java/our/yurivongella/instagramclone/service/MemberService.java
  src/test/java/our/yurivongella/instagramclone/service/MemberServiceTest.java
Labels: refactoring

#31 Update README.md
  README.md
Labels: good first issue

#33 Comment
  build.gradle
  codecov.yml
  src/main/java/our/yurivongella/instagramclone/config/SecurityConfig.java
  src/main/java/our/yurivongella/instagramclone/controller/CommentController.java
  src/main/java/our/yurivongella/instagramclone/controller/PostController.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/CommentCreateDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/comment/CommentList.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/comment/ProcessStatus.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/CommentResponseDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/MemberDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/PostReadResponseDto.java
  src/main/java/our/yurivongella/instagramclone/domain/comment/Comment.java
  src/main/java/our/yurivongella/instagramclone/domain/comment/CommentLike.java
  src/main/java/our/yurivongella/instagramclone/domain/comment/CommentLikeRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/comment/CommentRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/member/Member.java
  src/main/java/our/yurivongella/instagramclone/domain/post/Post.java
  src/main/java/our/yurivongella/instagramclone/service/CommentService.java
  src/main/java/our/yurivongella/instagramclone/service/PostService.java
  src/test/java/our/yurivongella/instagramclone/service/CommentServiceTest.java
Labels: enhancement

#39 build : fix dockerfile
  Dockerfile
  build.gradle
Labels: build

#40 chore: Member Entity 컬럼 변경 및 추가
  src/main/java/our/yurivongella/instagramclone/controller/dto/MemberResponseDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/SigninRequestDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/SignupRequestDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/TokenRequestDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/MemberDto.java
  src/main/java/our/yurivongella/instagramclone/domain/member/Authority.java
  src/main/java/our/yurivongella/instagramclone/domain/member/Member.java
  src/main/java/our/yurivongella/instagramclone/service/CommentService.java
  src/test/java/our/yurivongella/instagramclone/controller/dto/MemberDtoTest.java
  src/test/java/our/yurivongella/instagramclone/controller/dto/MemberResponseDtoTest.java
  src/test/java/our/yurivongella/instagramclone/service/AuthServiceTest.java
  src/test/java/our/yurivongella/instagramclone/service/CommentServiceTest.java
  src/test/java/our/yurivongella/instagramclone/service/CustomUserDetailsServiceTest.java
  src/test/java/our/yurivongella/instagramclone/service/MemberServiceTest.java
  src/test/java/our/yurivongella/instagramclone/service/PostServiceTest.java
Labels: enhancement, refactoring

#43 feat : Add Web Cors h2-console
  src/main/resources/application.yml
Labels: enhancement

#45 refactor: RESTful 형식에 맞춰서 API URI 형식 수정
  src/main/java/our/yurivongella/instagramclone/controller/AuthController.java
  src/main/java/our/yurivongella/instagramclone/controller/CommentController.java
  src/main/java/our/yurivongella/instagramclone/controller/MemberController.java
  src/main/java/our/yurivongella/instagramclone/controller/PostController.java
  src/main/java/our/yurivongella/instagramclone/domain/member/Member.java
  src/main/java/our/yurivongella/instagramclone/service/MemberService.java
  src/test/java/our/yurivongella/instagramclone/service/MemberServiceTest.java
Labels: refactoring

#46 feat: Exception Handling 추가
  src/main/java/our/yurivongella/instagramclone/domain/member/MemberRepository.java
  src/main/java/our/yurivongella/instagramclone/exception/CustomException.java
  src/main/java/our/yurivongella/instagramclone/exception/ErrorCode.java
  src/main/java/our/yurivongella/instagramclone/exception/ErrorResponse.java
  src/main/java/our/yurivongella/instagramclone/exception/GlobalExceptionHandler.java
  src/main/java/our/yurivongella/instagramclone/jwt/TokenProvider.java
  src/main/java/our/yurivongella/instagramclone/service/AuthService.java
  src/main/java/our/yurivongella/instagramclone/service/MemberService.java
  src/main/java/our/yurivongella/instagramclone/util/SecurityUtil.java
  src/main/resources/application.yml
Labels: enhancement, refactoring

#54 Template title 수정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: pr

#55 인스타그램 Feed
  build.gradle
  src/main/java/our/yurivongella/instagramclone/controller/FeedController.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/MemberResponseDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/PostReadResponseDto.java
  src/main/java/our/yurivongella/instagramclone/domain/comment/CommentRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/member/Member.java
  src/main/java/our/yurivongella/instagramclone/domain/post/PostRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/refeshtoken/RefreshToken.java
  src/main/java/our/yurivongella/instagramclone/service/MemberService.java
  src/main/java/our/yurivongella/instagramclone/service/PostService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/our/yurivongella/instagramclone/domain/comment/CommentRepositoryTest.java
  src/test/java/our/yurivongella/instagramclone/domain/post/PostRepositoryTest.java
  src/test/java/our/yurivongella/instagramclone/service/PostServiceTest.java
  src/test/resources/application.yml
Labels: enhancement

#63 Post Like 기능 추가, Count 필드 추가 및 조회 성능 개선, displayId 적용
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  src/main/java/our/yurivongella/instagramclone/config/JwtSecurityConfig.java
  src/main/java/our/yurivongella/instagramclone/config/SecurityConfig.java
  src/main/java/our/yurivongella/instagramclone/config/SwaggerConfig.java
  src/main/java/our/yurivongella/instagramclone/controller/AuthController.java
  src/main/java/our/yurivongella/instagramclone/controller/CommentController.java
  src/main/java/our/yurivongella/instagramclone/controller/FeedController.java
  src/main/java/our/yurivongella/instagramclone/controller/MemberController.java
  src/main/java/our/yurivongella/instagramclone/controller/PostController.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/MemberResponseDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/SigninRequestDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/SignupRequestDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/TokenRequestDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/comment/ProcessStatus.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/CommentResponseDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/MemberDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/PostCreateRequestDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/PostReadResponseDto.java
  src/main/java/our/yurivongella/instagramclone/domain/comment/Comment.java
  src/main/java/our/yurivongella/instagramclone/domain/comment/CommentLike.java
  src/main/java/our/yurivongella/instagramclone/domain/comment/CommentLikeRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/comment/CommentRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/follow/Follow.java
  src/main/java/our/yurivongella/instagramclone/domain/follow/FollowRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/member/Member.java
  src/main/java/our/yurivongella/instagramclone/domain/member/MemberRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/post/MediaUrl.java
  src/main/java/our/yurivongella/instagramclone/domain/post/Post.java
  src/main/java/our/yurivongella/instagramclone/domain/post/PostLike.java
  src/main/java/our/yurivongella/instagramclone/domain/post/PostLikeRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/post/PostRepository.java
  src/main/java/our/yurivongella/instagramclone/exception/ErrorCode.java
  src/main/java/our/yurivongella/instagramclone/exception/ErrorResponse.java
  src/main/java/our/yurivongella/instagramclone/exception/GlobalExceptionHandler.java
  src/main/java/our/yurivongella/instagramclone/jwt/JwtAccessDeniedHandler.java
  src/main/java/our/yurivongella/instagramclone/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/our/yurivongella/instagramclone/jwt/TokenProvider.java
  src/main/java/our/yurivongella/instagramclone/service/AuthService.java
  src/main/java/our/yurivongella/instagramclone/service/CommentService.java
  src/main/java/our/yurivongella/instagramclone/service/CustomUserDetailsService.java
  src/main/java/our/yurivongella/instagramclone/service/MemberService.java
  src/main/java/our/yurivongella/instagramclone/service/PostService.java
  src/main/java/our/yurivongella/instagramclone/util/SecurityUtil.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/our/yurivongella/instagramclone/controller/dto/MemberResponseDtoTest.java
  src/test/java/our/yurivongella/instagramclone/service/AuthServiceTest.java
  src/test/java/our/yurivongella/instagramclone/service/CommentServiceTest.java
  src/test/java/our/yurivongella/instagramclone/service/MemberServiceTest.java
  src/test/java/our/yurivongella/instagramclone/service/PostServiceTest.java
Labels: enhancement

#69 Like CORS issue
  src/main/java/our/yurivongella/instagramclone/controller/PostController.java
Labels: fix

#70 hotfix : cors on using put delete method
  src/main/java/our/yurivongella/instagramclone/config/WebConfig.java
Labels: hotfix

#71 Create DEV.yml
  .github/workflows/DEV.yml
Labels: test

#73 CI/CD
  .github/workflows/cicd.yml
Labels: build

#75 build: add master branch
  .github/workflows/gradle.yml
Labels: build

#66 feat: Profile API 추가 / 성능 개선을 위해 Member, Post 에 count 필드 추가
  src/main/java/our/yurivongella/instagramclone/controller/MemberController.java
  src/main/java/our/yurivongella/instagramclone/controller/PostController.java
  src/main/java/our/yurivongella/instagramclone/controller/ProfileController.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/MediaUrlDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/post/PostReadResponseDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/profile/ProfileDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/profile/ProfileMemberDto.java
  src/main/java/our/yurivongella/instagramclone/controller/dto/profile/ProfilePostDto.java
  src/main/java/our/yurivongella/instagramclone/domain/comment/Comment.java
  src/main/java/our/yurivongella/instagramclone/domain/follow/Follow.java
  src/main/java/our/yurivongella/instagramclone/domain/follow/FollowRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/member/Member.java
  src/main/java/our/yurivongella/instagramclone/domain/post/MediaUrl.java
  src/main/java/our/yurivongella/instagramclone/domain/post/Post.java
  src/main/java/our/yurivongella/instagramclone/domain/post/PostLikeRepository.java
  src/main/java/our/yurivongella/instagramclone/domain/post/PostRepository.java
  src/main/java/our/yurivongella/instagramclone/service/CommentService.java
  src/main/java/our/yurivongella/instagramclone/service/MemberService.java
  src/main/java/our/yurivongella/instagramclone/service/PostService.java
  src/main/java/our/yurivongella/instagramclone/service/ProfileService.java
  src/main/java/our/yurivongella/instagramclone/util/DateTimeUtil.java
  src/main/resources/data.sql
  src/test/java/our/yurivongella/instagramclone/service/CommentServiceTest.java
  src/test/java/our/yurivongella/instagramclone/service/MemberServiceTest.java
  src/test/java/our/yurivongella/instagramclone/service/PostServiceTest.java
  src/test/java/our/yurivongella/instagramclone/service/ProfileServiceTest.java
Labels: enhancement, refactoring, test
